#! /bin/sh

# Execute all the 'ip' command in the network namespace "${NETNS}"

# When openvpn is configured with 'redirect-gateway def1' it will try to add
# routes for ip addresses of the host which produces errors.
# From my current tests, 'redirect-gateway local' works fine

tun_in_netns()
{
    ip -n "${NETNS}" link show dev "$1" >/dev/null 2>&1
}

TUN="$4"
if [ "link" = "$1" ] && ( ! tun_in_netns "${TUN}" ); then
    # 'link' requires a different syntax when the interface is on the host
    exec ip $@ netns "${NETNS}"
else
    # Execute the command in the namespace
    exec ip -n "${NETNS}" $@
fi
